/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    'store-products': StoreProduct;
    categories: Category;
    'tag-registry': TagRegistry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'store-products': StoreProductsSelect<false> | StoreProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'tag-registry': TagRegistrySelect<false> | TagRegistrySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'api-key';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  /**
   * Auto-generated. Used as prefix for R2 filenames.
   */
  id: string;
  alt?: string | null;
  mediaType?: ('image' | 'svg' | 'video' | '3d') | null;
  /**
   * Extracted automatically on upload
   */
  videoMetadata?: {
    /**
     * seconds
     */
    duration?: number | null;
    fps?: number | null;
    /**
     * Start playing automatically
     */
    autoplay?: boolean | null;
    /**
     * Mute audio (required for autoplay)
     */
    muted?: boolean | null;
    /**
     * Loop playback infinitely
     */
    loop?: boolean | null;
    /**
     * Show playback controls
     */
    controls?: boolean | null;
    /**
     * Play inline on iOS (no fullscreen)
     */
    playsinline?: boolean | null;
  };
  /**
   * Auto-generated AVIF variants
   */
  variants?:
    | {
        url: string;
        width: number;
        height: number;
        fileSize?: number | null;
        id?: string | null;
      }[]
    | null;
  processingMetadata?: {
    variants?: string | null;
    processedAt?: string | null;
  };
  /**
   * SVG markup for inline HTML use (XML declaration stripped)
   */
  svgContent?: string | null;
  r2Url?: string | null;
  avifQuality?: {
    usePerVariantQuality?: boolean | null;
    colorQuality?: number | null;
    alphaQuality?: number | null;
    colorQuality_600?: number | null;
    alphaQuality_600?: number | null;
    colorQuality_1200?: number | null;
    alphaQuality_1200?: number | null;
    colorQuality_3000?: number | null;
    alphaQuality_3000?: number | null;
    colorQuality_full?: number | null;
    alphaQuality_full?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  slug: string;
  category?: (number | null) | Category;
  featuredImage?: (string | null) | Media;
  /**
   * Product page media gallery
   */
  mediaGallery?: {
    /**
     * Drag to reorder.
     */
    items?:
      | {
          media: string | Media;
          width?: ('full' | 'half' | 'quarter' | 'third') | null;
          display?: ('all' | 'desktop' | 'mobile') | null;
          /**
           * CSS padding on container element
           */
          padding?: string | null;
          /**
           * Extra CSS classes on container
           */
          customClasses?: string | null;
          /**
           * Inline CSS on inner wrapper
           */
          customStyle?: string | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'singleMedia';
        }[]
      | null;
  };
  infoPanel?:
    | (
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            displayMode?: ('fixed' | 'collapsible') | null;
            openByDefault?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'info-item';
          }
        | {
            rows?:
              | {
                  label: string;
                  value?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-products".
 */
export interface StoreProduct {
  id: number;
  title: string;
  slug: string;
  featuredImage?: (string | null) | Media;
  /**
   * Product page media gallery
   */
  mediaGallery?: {
    /**
     * Drag to reorder.
     */
    items?:
      | {
          media: string | Media;
          width?: ('full' | 'half' | 'quarter' | 'third') | null;
          display?: ('all' | 'desktop' | 'mobile') | null;
          /**
           * CSS padding on container element
           */
          padding?: string | null;
          /**
           * Extra CSS classes on container
           */
          customClasses?: string | null;
          /**
           * Inline CSS on inner wrapper
           */
          customStyle?: string | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'singleMedia';
        }[]
      | null;
  };
  infoPanel?:
    | (
        | {
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            displayMode?: ('fixed' | 'collapsible') | null;
            openByDefault?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'info-item';
          }
        | {
            rows?:
              | {
                  label: string;
                  value?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tag-registry".
 */
export interface TagRegistry {
  id: number;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'store-products';
        value: number | StoreProduct;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tag-registry';
        value: number | TagRegistry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  mediaType?: T;
  videoMetadata?:
    | T
    | {
        duration?: T;
        fps?: T;
        autoplay?: T;
        muted?: T;
        loop?: T;
        controls?: T;
        playsinline?: T;
      };
  variants?:
    | T
    | {
        url?: T;
        width?: T;
        height?: T;
        fileSize?: T;
        id?: T;
      };
  processingMetadata?:
    | T
    | {
        variants?: T;
        processedAt?: T;
      };
  svgContent?: T;
  r2Url?: T;
  avifQuality?:
    | T
    | {
        usePerVariantQuality?: T;
        colorQuality?: T;
        alphaQuality?: T;
        colorQuality_600?: T;
        alphaQuality_600?: T;
        colorQuality_1200?: T;
        alphaQuality_1200?: T;
        colorQuality_3000?: T;
        alphaQuality_3000?: T;
        colorQuality_full?: T;
        alphaQuality_full?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  mediaGallery?:
    | T
    | {
        items?:
          | T
          | {
              singleMedia?:
                | T
                | {
                    media?: T;
                    width?: T;
                    display?: T;
                    padding?: T;
                    customClasses?: T;
                    customStyle?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  infoPanel?:
    | T
    | {
        'info-item'?:
          | T
          | {
              title?: T;
              content?: T;
              displayMode?: T;
              openByDefault?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-products_select".
 */
export interface StoreProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  mediaGallery?:
    | T
    | {
        items?:
          | T
          | {
              singleMedia?:
                | T
                | {
                    media?: T;
                    width?: T;
                    display?: T;
                    padding?: T;
                    customClasses?: T;
                    customStyle?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  infoPanel?:
    | T
    | {
        'info-item'?:
          | T
          | {
              title?: T;
              content?: T;
              displayMode?: T;
              openByDefault?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tag-registry_select".
 */
export interface TagRegistrySelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}